// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qrlwallet.proto

/*
Package qrl is a generated protocol buffer package.

It is generated from these files:
	qrlwallet.proto

It has these top-level messages:
	AddNewAddressReq
	AddNewAddressResp
	AddAddressFromSeedReq
	AddAddressFromSeedResp
	ListAddressesReq
	ListAddressesResp
	RemoveAddressReq
	RemoveAddressResp
	EncryptWalletReq
	EncryptWalletResp
	UnlockWalletReq
	UnlockWalletResp
	LockWalletReq
	LockWalletResp
	GetRecoverySeedsReq
	GetRecoverySeedsResp
	GetWalletInfoReq
	GetWalletInfoResp
	RelayTransferTxnReq
	RelayMessageTxnReq
	RelayTokenTxnReq
	RelayTransferTokenTxnReq
	RelaySlaveTxnReq
	RelayTxnResp
	ChangePassphraseReq
	ChangePassphraseResp
	TransactionReq
	TransactionResp
	BalanceReq
	BalanceResp
	OTSReq
	OTSResp
	HeightReq
	HeightResp
	BlockReq
	BlockResp
	BlockByNumberReq
*/
package qrlwallet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import qrl1 "github.com/theQRL/walletd-rest-proxy/generated"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddNewAddressReq struct {
	Height       uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	HashFunction string `protobuf:"bytes,2,opt,name=hash_function,json=hashFunction" json:"hash_function,omitempty"`
}

func (m *AddNewAddressReq) Reset()                    { *m = AddNewAddressReq{} }
func (m *AddNewAddressReq) String() string            { return proto.CompactTextString(m) }
func (*AddNewAddressReq) ProtoMessage()               {}
func (*AddNewAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddNewAddressReq) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AddNewAddressReq) GetHashFunction() string {
	if m != nil {
		return m.HashFunction
	}
	return ""
}

type AddNewAddressResp struct {
	Code    uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *AddNewAddressResp) Reset()                    { *m = AddNewAddressResp{} }
func (m *AddNewAddressResp) String() string            { return proto.CompactTextString(m) }
func (*AddNewAddressResp) ProtoMessage()               {}
func (*AddNewAddressResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddNewAddressResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddNewAddressResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *AddNewAddressResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AddAddressFromSeedReq struct {
	Seed string `protobuf:"bytes,1,opt,name=seed" json:"seed,omitempty"`
}

func (m *AddAddressFromSeedReq) Reset()                    { *m = AddAddressFromSeedReq{} }
func (m *AddAddressFromSeedReq) String() string            { return proto.CompactTextString(m) }
func (*AddAddressFromSeedReq) ProtoMessage()               {}
func (*AddAddressFromSeedReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddAddressFromSeedReq) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

type AddAddressFromSeedResp struct {
	Code    uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *AddAddressFromSeedResp) Reset()                    { *m = AddAddressFromSeedResp{} }
func (m *AddAddressFromSeedResp) String() string            { return proto.CompactTextString(m) }
func (*AddAddressFromSeedResp) ProtoMessage()               {}
func (*AddAddressFromSeedResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddAddressFromSeedResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddAddressFromSeedResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *AddAddressFromSeedResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ListAddressesReq struct {
}

func (m *ListAddressesReq) Reset()                    { *m = ListAddressesReq{} }
func (m *ListAddressesReq) String() string            { return proto.CompactTextString(m) }
func (*ListAddressesReq) ProtoMessage()               {}
func (*ListAddressesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListAddressesResp struct {
	Code      uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error     string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Addresses []string `protobuf:"bytes,3,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *ListAddressesResp) Reset()                    { *m = ListAddressesResp{} }
func (m *ListAddressesResp) String() string            { return proto.CompactTextString(m) }
func (*ListAddressesResp) ProtoMessage()               {}
func (*ListAddressesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListAddressesResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListAddressesResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListAddressesResp) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type RemoveAddressReq struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *RemoveAddressReq) Reset()                    { *m = RemoveAddressReq{} }
func (m *RemoveAddressReq) String() string            { return proto.CompactTextString(m) }
func (*RemoveAddressReq) ProtoMessage()               {}
func (*RemoveAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveAddressReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RemoveAddressResp struct {
	Code  uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *RemoveAddressResp) Reset()                    { *m = RemoveAddressResp{} }
func (m *RemoveAddressResp) String() string            { return proto.CompactTextString(m) }
func (*RemoveAddressResp) ProtoMessage()               {}
func (*RemoveAddressResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RemoveAddressResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RemoveAddressResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EncryptWalletReq struct {
	Passphrase string `protobuf:"bytes,1,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *EncryptWalletReq) Reset()                    { *m = EncryptWalletReq{} }
func (m *EncryptWalletReq) String() string            { return proto.CompactTextString(m) }
func (*EncryptWalletReq) ProtoMessage()               {}
func (*EncryptWalletReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EncryptWalletReq) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type EncryptWalletResp struct {
	Code  uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *EncryptWalletResp) Reset()                    { *m = EncryptWalletResp{} }
func (m *EncryptWalletResp) String() string            { return proto.CompactTextString(m) }
func (*EncryptWalletResp) ProtoMessage()               {}
func (*EncryptWalletResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EncryptWalletResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EncryptWalletResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UnlockWalletReq struct {
	Passphrase string `protobuf:"bytes,1,opt,name=passphrase" json:"passphrase,omitempty"`
}

func (m *UnlockWalletReq) Reset()                    { *m = UnlockWalletReq{} }
func (m *UnlockWalletReq) String() string            { return proto.CompactTextString(m) }
func (*UnlockWalletReq) ProtoMessage()               {}
func (*UnlockWalletReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UnlockWalletReq) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type UnlockWalletResp struct {
	Code  uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *UnlockWalletResp) Reset()                    { *m = UnlockWalletResp{} }
func (m *UnlockWalletResp) String() string            { return proto.CompactTextString(m) }
func (*UnlockWalletResp) ProtoMessage()               {}
func (*UnlockWalletResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UnlockWalletResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UnlockWalletResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LockWalletReq struct {
}

func (m *LockWalletReq) Reset()                    { *m = LockWalletReq{} }
func (m *LockWalletReq) String() string            { return proto.CompactTextString(m) }
func (*LockWalletReq) ProtoMessage()               {}
func (*LockWalletReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type LockWalletResp struct {
	Code  uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *LockWalletResp) Reset()                    { *m = LockWalletResp{} }
func (m *LockWalletResp) String() string            { return proto.CompactTextString(m) }
func (*LockWalletResp) ProtoMessage()               {}
func (*LockWalletResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LockWalletResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LockWalletResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetRecoverySeedsReq struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *GetRecoverySeedsReq) Reset()                    { *m = GetRecoverySeedsReq{} }
func (m *GetRecoverySeedsReq) String() string            { return proto.CompactTextString(m) }
func (*GetRecoverySeedsReq) ProtoMessage()               {}
func (*GetRecoverySeedsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetRecoverySeedsReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetRecoverySeedsResp struct {
	Code     uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Hexseed  string `protobuf:"bytes,3,opt,name=hexseed" json:"hexseed,omitempty"`
	Mnemonic string `protobuf:"bytes,4,opt,name=mnemonic" json:"mnemonic,omitempty"`
}

func (m *GetRecoverySeedsResp) Reset()                    { *m = GetRecoverySeedsResp{} }
func (m *GetRecoverySeedsResp) String() string            { return proto.CompactTextString(m) }
func (*GetRecoverySeedsResp) ProtoMessage()               {}
func (*GetRecoverySeedsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetRecoverySeedsResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRecoverySeedsResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetRecoverySeedsResp) GetHexseed() string {
	if m != nil {
		return m.Hexseed
	}
	return ""
}

func (m *GetRecoverySeedsResp) GetMnemonic() string {
	if m != nil {
		return m.Mnemonic
	}
	return ""
}

type GetWalletInfoReq struct {
}

func (m *GetWalletInfoReq) Reset()                    { *m = GetWalletInfoReq{} }
func (m *GetWalletInfoReq) String() string            { return proto.CompactTextString(m) }
func (*GetWalletInfoReq) ProtoMessage()               {}
func (*GetWalletInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetWalletInfoResp struct {
	Code         uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error        string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Version      uint32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	AddressCount uint64 `protobuf:"varint,4,opt,name=address_count,json=addressCount" json:"address_count,omitempty"`
	IsEncrypted  bool   `protobuf:"varint,5,opt,name=is_encrypted,json=isEncrypted" json:"is_encrypted,omitempty"`
}

func (m *GetWalletInfoResp) Reset()                    { *m = GetWalletInfoResp{} }
func (m *GetWalletInfoResp) String() string            { return proto.CompactTextString(m) }
func (*GetWalletInfoResp) ProtoMessage()               {}
func (*GetWalletInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetWalletInfoResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetWalletInfoResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetWalletInfoResp) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetWalletInfoResp) GetAddressCount() uint64 {
	if m != nil {
		return m.AddressCount
	}
	return 0
}

func (m *GetWalletInfoResp) GetIsEncrypted() bool {
	if m != nil {
		return m.IsEncrypted
	}
	return false
}

type RelayTransferTxnReq struct {
	AddressesTo   []string `protobuf:"bytes,1,rep,name=addresses_to,json=addressesTo" json:"addresses_to,omitempty"`
	Amounts       []uint64 `protobuf:"varint,2,rep,packed,name=amounts" json:"amounts,omitempty"`
	Fee           uint64   `protobuf:"varint,3,opt,name=fee" json:"fee,omitempty"`
	MasterAddress string   `protobuf:"bytes,4,opt,name=master_address,json=masterAddress" json:"master_address,omitempty"`
	SignerAddress string   `protobuf:"bytes,5,opt,name=signer_address,json=signerAddress" json:"signer_address,omitempty"`
	OtsIndex      uint64   `protobuf:"varint,6,opt,name=ots_index,json=otsIndex" json:"ots_index,omitempty"`
}

func (m *RelayTransferTxnReq) Reset()                    { *m = RelayTransferTxnReq{} }
func (m *RelayTransferTxnReq) String() string            { return proto.CompactTextString(m) }
func (*RelayTransferTxnReq) ProtoMessage()               {}
func (*RelayTransferTxnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *RelayTransferTxnReq) GetAddressesTo() []string {
	if m != nil {
		return m.AddressesTo
	}
	return nil
}

func (m *RelayTransferTxnReq) GetAmounts() []uint64 {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *RelayTransferTxnReq) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RelayTransferTxnReq) GetMasterAddress() string {
	if m != nil {
		return m.MasterAddress
	}
	return ""
}

func (m *RelayTransferTxnReq) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *RelayTransferTxnReq) GetOtsIndex() uint64 {
	if m != nil {
		return m.OtsIndex
	}
	return 0
}

type RelayMessageTxnReq struct {
	Message       string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Fee           uint64 `protobuf:"varint,2,opt,name=fee" json:"fee,omitempty"`
	MasterAddress string `protobuf:"bytes,3,opt,name=master_address,json=masterAddress" json:"master_address,omitempty"`
	SignerAddress string `protobuf:"bytes,4,opt,name=signer_address,json=signerAddress" json:"signer_address,omitempty"`
	OtsIndex      uint64 `protobuf:"varint,5,opt,name=ots_index,json=otsIndex" json:"ots_index,omitempty"`
}

func (m *RelayMessageTxnReq) Reset()                    { *m = RelayMessageTxnReq{} }
func (m *RelayMessageTxnReq) String() string            { return proto.CompactTextString(m) }
func (*RelayMessageTxnReq) ProtoMessage()               {}
func (*RelayMessageTxnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RelayMessageTxnReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RelayMessageTxnReq) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RelayMessageTxnReq) GetMasterAddress() string {
	if m != nil {
		return m.MasterAddress
	}
	return ""
}

func (m *RelayMessageTxnReq) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *RelayMessageTxnReq) GetOtsIndex() uint64 {
	if m != nil {
		return m.OtsIndex
	}
	return 0
}

type RelayTokenTxnReq struct {
	Symbol        string   `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner         string   `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Decimals      uint64   `protobuf:"varint,4,opt,name=decimals" json:"decimals,omitempty"`
	Addresses     []string `protobuf:"bytes,5,rep,name=addresses" json:"addresses,omitempty"`
	Amounts       []uint64 `protobuf:"varint,6,rep,packed,name=amounts" json:"amounts,omitempty"`
	Fee           uint64   `protobuf:"varint,7,opt,name=fee" json:"fee,omitempty"`
	MasterAddress string   `protobuf:"bytes,8,opt,name=master_address,json=masterAddress" json:"master_address,omitempty"`
	SignerAddress string   `protobuf:"bytes,9,opt,name=signer_address,json=signerAddress" json:"signer_address,omitempty"`
	OtsIndex      uint64   `protobuf:"varint,10,opt,name=ots_index,json=otsIndex" json:"ots_index,omitempty"`
}

func (m *RelayTokenTxnReq) Reset()                    { *m = RelayTokenTxnReq{} }
func (m *RelayTokenTxnReq) String() string            { return proto.CompactTextString(m) }
func (*RelayTokenTxnReq) ProtoMessage()               {}
func (*RelayTokenTxnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RelayTokenTxnReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *RelayTokenTxnReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RelayTokenTxnReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RelayTokenTxnReq) GetDecimals() uint64 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *RelayTokenTxnReq) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *RelayTokenTxnReq) GetAmounts() []uint64 {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *RelayTokenTxnReq) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RelayTokenTxnReq) GetMasterAddress() string {
	if m != nil {
		return m.MasterAddress
	}
	return ""
}

func (m *RelayTokenTxnReq) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *RelayTokenTxnReq) GetOtsIndex() uint64 {
	if m != nil {
		return m.OtsIndex
	}
	return 0
}

type RelayTransferTokenTxnReq struct {
	AddressesTo   []string `protobuf:"bytes,1,rep,name=addresses_to,json=addressesTo" json:"addresses_to,omitempty"`
	TokenTxhash   string   `protobuf:"bytes,2,opt,name=token_txhash,json=tokenTxhash" json:"token_txhash,omitempty"`
	Amounts       []uint64 `protobuf:"varint,3,rep,packed,name=amounts" json:"amounts,omitempty"`
	Fee           uint64   `protobuf:"varint,4,opt,name=fee" json:"fee,omitempty"`
	MasterAddress string   `protobuf:"bytes,5,opt,name=master_address,json=masterAddress" json:"master_address,omitempty"`
	SignerAddress string   `protobuf:"bytes,6,opt,name=signer_address,json=signerAddress" json:"signer_address,omitempty"`
	OtsIndex      uint64   `protobuf:"varint,7,opt,name=ots_index,json=otsIndex" json:"ots_index,omitempty"`
}

func (m *RelayTransferTokenTxnReq) Reset()                    { *m = RelayTransferTokenTxnReq{} }
func (m *RelayTransferTokenTxnReq) String() string            { return proto.CompactTextString(m) }
func (*RelayTransferTokenTxnReq) ProtoMessage()               {}
func (*RelayTransferTokenTxnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RelayTransferTokenTxnReq) GetAddressesTo() []string {
	if m != nil {
		return m.AddressesTo
	}
	return nil
}

func (m *RelayTransferTokenTxnReq) GetTokenTxhash() string {
	if m != nil {
		return m.TokenTxhash
	}
	return ""
}

func (m *RelayTransferTokenTxnReq) GetAmounts() []uint64 {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *RelayTransferTokenTxnReq) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RelayTransferTokenTxnReq) GetMasterAddress() string {
	if m != nil {
		return m.MasterAddress
	}
	return ""
}

func (m *RelayTransferTokenTxnReq) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *RelayTransferTokenTxnReq) GetOtsIndex() uint64 {
	if m != nil {
		return m.OtsIndex
	}
	return 0
}

type RelaySlaveTxnReq struct {
	SlavePks      [][]byte `protobuf:"bytes,1,rep,name=slave_pks,json=slavePks,proto3" json:"slave_pks,omitempty"`
	AccessTypes   []uint32 `protobuf:"varint,2,rep,packed,name=access_types,json=accessTypes" json:"access_types,omitempty"`
	Fee           uint64   `protobuf:"varint,3,opt,name=fee" json:"fee,omitempty"`
	MasterAddress string   `protobuf:"bytes,4,opt,name=master_address,json=masterAddress" json:"master_address,omitempty"`
	SignerAddress string   `protobuf:"bytes,5,opt,name=signer_address,json=signerAddress" json:"signer_address,omitempty"`
	OtsIndex      uint64   `protobuf:"varint,6,opt,name=ots_index,json=otsIndex" json:"ots_index,omitempty"`
}

func (m *RelaySlaveTxnReq) Reset()                    { *m = RelaySlaveTxnReq{} }
func (m *RelaySlaveTxnReq) String() string            { return proto.CompactTextString(m) }
func (*RelaySlaveTxnReq) ProtoMessage()               {}
func (*RelaySlaveTxnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RelaySlaveTxnReq) GetSlavePks() [][]byte {
	if m != nil {
		return m.SlavePks
	}
	return nil
}

func (m *RelaySlaveTxnReq) GetAccessTypes() []uint32 {
	if m != nil {
		return m.AccessTypes
	}
	return nil
}

func (m *RelaySlaveTxnReq) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *RelaySlaveTxnReq) GetMasterAddress() string {
	if m != nil {
		return m.MasterAddress
	}
	return ""
}

func (m *RelaySlaveTxnReq) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *RelaySlaveTxnReq) GetOtsIndex() uint64 {
	if m != nil {
		return m.OtsIndex
	}
	return 0
}

type RelayTxnResp struct {
	Code  uint32            `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Tx    *qrl1.Transaction `protobuf:"bytes,3,opt,name=tx" json:"tx,omitempty"`
}

func (m *RelayTxnResp) Reset()                    { *m = RelayTxnResp{} }
func (m *RelayTxnResp) String() string            { return proto.CompactTextString(m) }
func (*RelayTxnResp) ProtoMessage()               {}
func (*RelayTxnResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RelayTxnResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RelayTxnResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RelayTxnResp) GetTx() *qrl1.Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type ChangePassphraseReq struct {
	OldPassphrase string `protobuf:"bytes,1,opt,name=oldPassphrase" json:"oldPassphrase,omitempty"`
	NewPassphrase string `protobuf:"bytes,2,opt,name=newPassphrase" json:"newPassphrase,omitempty"`
}

func (m *ChangePassphraseReq) Reset()                    { *m = ChangePassphraseReq{} }
func (m *ChangePassphraseReq) String() string            { return proto.CompactTextString(m) }
func (*ChangePassphraseReq) ProtoMessage()               {}
func (*ChangePassphraseReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ChangePassphraseReq) GetOldPassphrase() string {
	if m != nil {
		return m.OldPassphrase
	}
	return ""
}

func (m *ChangePassphraseReq) GetNewPassphrase() string {
	if m != nil {
		return m.NewPassphrase
	}
	return ""
}

type ChangePassphraseResp struct {
	Code  uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ChangePassphraseResp) Reset()                    { *m = ChangePassphraseResp{} }
func (m *ChangePassphraseResp) String() string            { return proto.CompactTextString(m) }
func (*ChangePassphraseResp) ProtoMessage()               {}
func (*ChangePassphraseResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ChangePassphraseResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChangePassphraseResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type TransactionReq struct {
	TxHash string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
}

func (m *TransactionReq) Reset()                    { *m = TransactionReq{} }
func (m *TransactionReq) String() string            { return proto.CompactTextString(m) }
func (*TransactionReq) ProtoMessage()               {}
func (*TransactionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *TransactionReq) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type TransactionResp struct {
	Code          uint32            `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error         string            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Tx            *qrl1.Transaction `protobuf:"bytes,3,opt,name=tx" json:"tx,omitempty"`
	Confirmations uint64            `protobuf:"varint,4,opt,name=confirmations" json:"confirmations,omitempty"`
}

func (m *TransactionResp) Reset()                    { *m = TransactionResp{} }
func (m *TransactionResp) String() string            { return proto.CompactTextString(m) }
func (*TransactionResp) ProtoMessage()               {}
func (*TransactionResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *TransactionResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TransactionResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TransactionResp) GetTx() *qrl1.Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *TransactionResp) GetConfirmations() uint64 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

type BalanceReq struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *BalanceReq) Reset()                    { *m = BalanceReq{} }
func (m *BalanceReq) String() string            { return proto.CompactTextString(m) }
func (*BalanceReq) ProtoMessage()               {}
func (*BalanceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *BalanceReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type BalanceResp struct {
	Code    uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Balance uint64 `protobuf:"varint,3,opt,name=balance" json:"balance,omitempty"`
}

func (m *BalanceResp) Reset()                    { *m = BalanceResp{} }
func (m *BalanceResp) String() string            { return proto.CompactTextString(m) }
func (*BalanceResp) ProtoMessage()               {}
func (*BalanceResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *BalanceResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BalanceResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BalanceResp) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type OTSReq struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *OTSReq) Reset()                    { *m = OTSReq{} }
func (m *OTSReq) String() string            { return proto.CompactTextString(m) }
func (*OTSReq) ProtoMessage()               {}
func (*OTSReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *OTSReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type OTSResp struct {
	Code               uint32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error              string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	OtsBitfield        [][]byte `protobuf:"bytes,3,rep,name=ots_bitfield,json=otsBitfield,proto3" json:"ots_bitfield,omitempty"`
	NextUnusedOtsIndex uint64   `protobuf:"varint,4,opt,name=next_unused_ots_index,json=nextUnusedOtsIndex" json:"next_unused_ots_index,omitempty"`
}

func (m *OTSResp) Reset()                    { *m = OTSResp{} }
func (m *OTSResp) String() string            { return proto.CompactTextString(m) }
func (*OTSResp) ProtoMessage()               {}
func (*OTSResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *OTSResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *OTSResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *OTSResp) GetOtsBitfield() [][]byte {
	if m != nil {
		return m.OtsBitfield
	}
	return nil
}

func (m *OTSResp) GetNextUnusedOtsIndex() uint64 {
	if m != nil {
		return m.NextUnusedOtsIndex
	}
	return 0
}

type HeightReq struct {
}

func (m *HeightReq) Reset()                    { *m = HeightReq{} }
func (m *HeightReq) String() string            { return proto.CompactTextString(m) }
func (*HeightReq) ProtoMessage()               {}
func (*HeightReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type HeightResp struct {
	Code   uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Height uint64 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
}

func (m *HeightResp) Reset()                    { *m = HeightResp{} }
func (m *HeightResp) String() string            { return proto.CompactTextString(m) }
func (*HeightResp) ProtoMessage()               {}
func (*HeightResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *HeightResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HeightResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *HeightResp) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockReq struct {
	HeaderHash string `protobuf:"bytes,1,opt,name=header_hash,json=headerHash" json:"header_hash,omitempty"`
}

func (m *BlockReq) Reset()                    { *m = BlockReq{} }
func (m *BlockReq) String() string            { return proto.CompactTextString(m) }
func (*BlockReq) ProtoMessage()               {}
func (*BlockReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *BlockReq) GetHeaderHash() string {
	if m != nil {
		return m.HeaderHash
	}
	return ""
}

type BlockResp struct {
	Code  uint32      `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Block *qrl1.Block `protobuf:"bytes,3,opt,name=block" json:"block,omitempty"`
}

func (m *BlockResp) Reset()                    { *m = BlockResp{} }
func (m *BlockResp) String() string            { return proto.CompactTextString(m) }
func (*BlockResp) ProtoMessage()               {}
func (*BlockResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *BlockResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BlockResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BlockResp) GetBlock() *qrl1.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type BlockByNumberReq struct {
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number,omitempty"`
}

func (m *BlockByNumberReq) Reset()                    { *m = BlockByNumberReq{} }
func (m *BlockByNumberReq) String() string            { return proto.CompactTextString(m) }
func (*BlockByNumberReq) ProtoMessage()               {}
func (*BlockByNumberReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *BlockByNumberReq) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*AddNewAddressReq)(nil), "qrl.AddNewAddressReq")
	proto.RegisterType((*AddNewAddressResp)(nil), "qrl.AddNewAddressResp")
	proto.RegisterType((*AddAddressFromSeedReq)(nil), "qrl.AddAddressFromSeedReq")
	proto.RegisterType((*AddAddressFromSeedResp)(nil), "qrl.AddAddressFromSeedResp")
	proto.RegisterType((*ListAddressesReq)(nil), "qrl.ListAddressesReq")
	proto.RegisterType((*ListAddressesResp)(nil), "qrl.ListAddressesResp")
	proto.RegisterType((*RemoveAddressReq)(nil), "qrl.RemoveAddressReq")
	proto.RegisterType((*RemoveAddressResp)(nil), "qrl.RemoveAddressResp")
	proto.RegisterType((*EncryptWalletReq)(nil), "qrl.EncryptWalletReq")
	proto.RegisterType((*EncryptWalletResp)(nil), "qrl.EncryptWalletResp")
	proto.RegisterType((*UnlockWalletReq)(nil), "qrl.UnlockWalletReq")
	proto.RegisterType((*UnlockWalletResp)(nil), "qrl.UnlockWalletResp")
	proto.RegisterType((*LockWalletReq)(nil), "qrl.LockWalletReq")
	proto.RegisterType((*LockWalletResp)(nil), "qrl.LockWalletResp")
	proto.RegisterType((*GetRecoverySeedsReq)(nil), "qrl.GetRecoverySeedsReq")
	proto.RegisterType((*GetRecoverySeedsResp)(nil), "qrl.GetRecoverySeedsResp")
	proto.RegisterType((*GetWalletInfoReq)(nil), "qrl.GetWalletInfoReq")
	proto.RegisterType((*GetWalletInfoResp)(nil), "qrl.GetWalletInfoResp")
	proto.RegisterType((*RelayTransferTxnReq)(nil), "qrl.RelayTransferTxnReq")
	proto.RegisterType((*RelayMessageTxnReq)(nil), "qrl.RelayMessageTxnReq")
	proto.RegisterType((*RelayTokenTxnReq)(nil), "qrl.RelayTokenTxnReq")
	proto.RegisterType((*RelayTransferTokenTxnReq)(nil), "qrl.RelayTransferTokenTxnReq")
	proto.RegisterType((*RelaySlaveTxnReq)(nil), "qrl.RelaySlaveTxnReq")
	proto.RegisterType((*RelayTxnResp)(nil), "qrl.RelayTxnResp")
	proto.RegisterType((*ChangePassphraseReq)(nil), "qrl.ChangePassphraseReq")
	proto.RegisterType((*ChangePassphraseResp)(nil), "qrl.ChangePassphraseResp")
	proto.RegisterType((*TransactionReq)(nil), "qrl.TransactionReq")
	proto.RegisterType((*TransactionResp)(nil), "qrl.TransactionResp")
	proto.RegisterType((*BalanceReq)(nil), "qrl.BalanceReq")
	proto.RegisterType((*BalanceResp)(nil), "qrl.BalanceResp")
	proto.RegisterType((*OTSReq)(nil), "qrl.OTSReq")
	proto.RegisterType((*OTSResp)(nil), "qrl.OTSResp")
	proto.RegisterType((*HeightReq)(nil), "qrl.HeightReq")
	proto.RegisterType((*HeightResp)(nil), "qrl.HeightResp")
	proto.RegisterType((*BlockReq)(nil), "qrl.BlockReq")
	proto.RegisterType((*BlockResp)(nil), "qrl.BlockResp")
	proto.RegisterType((*BlockByNumberReq)(nil), "qrl.BlockByNumberReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WalletAPI service

type WalletAPIClient interface {
	AddNewAddress(ctx context.Context, in *AddNewAddressReq, opts ...grpc.CallOption) (*AddNewAddressResp, error)
	AddAddressFromSeed(ctx context.Context, in *AddAddressFromSeedReq, opts ...grpc.CallOption) (*AddAddressFromSeedResp, error)
	ListAddresses(ctx context.Context, in *ListAddressesReq, opts ...grpc.CallOption) (*ListAddressesResp, error)
	RemoveAddress(ctx context.Context, in *RemoveAddressReq, opts ...grpc.CallOption) (*RemoveAddressResp, error)
	EncryptWallet(ctx context.Context, in *EncryptWalletReq, opts ...grpc.CallOption) (*EncryptWalletResp, error)
	LockWallet(ctx context.Context, in *LockWalletReq, opts ...grpc.CallOption) (*LockWalletResp, error)
	UnlockWallet(ctx context.Context, in *UnlockWalletReq, opts ...grpc.CallOption) (*UnlockWalletResp, error)
	GetRecoverySeeds(ctx context.Context, in *GetRecoverySeedsReq, opts ...grpc.CallOption) (*GetRecoverySeedsResp, error)
	GetWalletInfo(ctx context.Context, in *GetWalletInfoReq, opts ...grpc.CallOption) (*GetWalletInfoResp, error)
	RelayTransferTxn(ctx context.Context, in *RelayTransferTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error)
	RelayMessageTxn(ctx context.Context, in *RelayMessageTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error)
	RelayTokenTxn(ctx context.Context, in *RelayTokenTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error)
	RelayTransferTokenTxn(ctx context.Context, in *RelayTransferTokenTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error)
	RelaySlaveTxn(ctx context.Context, in *RelaySlaveTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error)
	ChangePassphrase(ctx context.Context, in *ChangePassphraseReq, opts ...grpc.CallOption) (*ChangePassphraseResp, error)
	GetTransaction(ctx context.Context, in *TransactionReq, opts ...grpc.CallOption) (*TransactionResp, error)
	GetBalance(ctx context.Context, in *BalanceReq, opts ...grpc.CallOption) (*BalanceResp, error)
	GetOTS(ctx context.Context, in *OTSReq, opts ...grpc.CallOption) (*OTSResp, error)
	GetHeight(ctx context.Context, in *HeightReq, opts ...grpc.CallOption) (*HeightResp, error)
	GetBlock(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockResp, error)
	GetBlockByNumber(ctx context.Context, in *BlockByNumberReq, opts ...grpc.CallOption) (*BlockResp, error)
}

type walletAPIClient struct {
	cc *grpc.ClientConn
}

func NewWalletAPIClient(cc *grpc.ClientConn) WalletAPIClient {
	return &walletAPIClient{cc}
}

func (c *walletAPIClient) AddNewAddress(ctx context.Context, in *AddNewAddressReq, opts ...grpc.CallOption) (*AddNewAddressResp, error) {
	out := new(AddNewAddressResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/AddNewAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) AddAddressFromSeed(ctx context.Context, in *AddAddressFromSeedReq, opts ...grpc.CallOption) (*AddAddressFromSeedResp, error) {
	out := new(AddAddressFromSeedResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/AddAddressFromSeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) ListAddresses(ctx context.Context, in *ListAddressesReq, opts ...grpc.CallOption) (*ListAddressesResp, error) {
	out := new(ListAddressesResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/ListAddresses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) RemoveAddress(ctx context.Context, in *RemoveAddressReq, opts ...grpc.CallOption) (*RemoveAddressResp, error) {
	out := new(RemoveAddressResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/RemoveAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) EncryptWallet(ctx context.Context, in *EncryptWalletReq, opts ...grpc.CallOption) (*EncryptWalletResp, error) {
	out := new(EncryptWalletResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/EncryptWallet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) LockWallet(ctx context.Context, in *LockWalletReq, opts ...grpc.CallOption) (*LockWalletResp, error) {
	out := new(LockWalletResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/LockWallet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) UnlockWallet(ctx context.Context, in *UnlockWalletReq, opts ...grpc.CallOption) (*UnlockWalletResp, error) {
	out := new(UnlockWalletResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/UnlockWallet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetRecoverySeeds(ctx context.Context, in *GetRecoverySeedsReq, opts ...grpc.CallOption) (*GetRecoverySeedsResp, error) {
	out := new(GetRecoverySeedsResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetRecoverySeeds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetWalletInfo(ctx context.Context, in *GetWalletInfoReq, opts ...grpc.CallOption) (*GetWalletInfoResp, error) {
	out := new(GetWalletInfoResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetWalletInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) RelayTransferTxn(ctx context.Context, in *RelayTransferTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error) {
	out := new(RelayTxnResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/RelayTransferTxn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) RelayMessageTxn(ctx context.Context, in *RelayMessageTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error) {
	out := new(RelayTxnResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/RelayMessageTxn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) RelayTokenTxn(ctx context.Context, in *RelayTokenTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error) {
	out := new(RelayTxnResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/RelayTokenTxn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) RelayTransferTokenTxn(ctx context.Context, in *RelayTransferTokenTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error) {
	out := new(RelayTxnResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/RelayTransferTokenTxn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) RelaySlaveTxn(ctx context.Context, in *RelaySlaveTxnReq, opts ...grpc.CallOption) (*RelayTxnResp, error) {
	out := new(RelayTxnResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/RelaySlaveTxn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) ChangePassphrase(ctx context.Context, in *ChangePassphraseReq, opts ...grpc.CallOption) (*ChangePassphraseResp, error) {
	out := new(ChangePassphraseResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/ChangePassphrase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetTransaction(ctx context.Context, in *TransactionReq, opts ...grpc.CallOption) (*TransactionResp, error) {
	out := new(TransactionResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetBalance(ctx context.Context, in *BalanceReq, opts ...grpc.CallOption) (*BalanceResp, error) {
	out := new(BalanceResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetOTS(ctx context.Context, in *OTSReq, opts ...grpc.CallOption) (*OTSResp, error) {
	out := new(OTSResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetOTS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetHeight(ctx context.Context, in *HeightReq, opts ...grpc.CallOption) (*HeightResp, error) {
	out := new(HeightResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetHeight", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetBlock(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockResp, error) {
	out := new(BlockResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAPIClient) GetBlockByNumber(ctx context.Context, in *BlockByNumberReq, opts ...grpc.CallOption) (*BlockResp, error) {
	out := new(BlockResp)
	err := grpc.Invoke(ctx, "/qrl.WalletAPI/GetBlockByNumber", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WalletAPI service

type WalletAPIServer interface {
	AddNewAddress(context.Context, *AddNewAddressReq) (*AddNewAddressResp, error)
	AddAddressFromSeed(context.Context, *AddAddressFromSeedReq) (*AddAddressFromSeedResp, error)
	ListAddresses(context.Context, *ListAddressesReq) (*ListAddressesResp, error)
	RemoveAddress(context.Context, *RemoveAddressReq) (*RemoveAddressResp, error)
	EncryptWallet(context.Context, *EncryptWalletReq) (*EncryptWalletResp, error)
	LockWallet(context.Context, *LockWalletReq) (*LockWalletResp, error)
	UnlockWallet(context.Context, *UnlockWalletReq) (*UnlockWalletResp, error)
	GetRecoverySeeds(context.Context, *GetRecoverySeedsReq) (*GetRecoverySeedsResp, error)
	GetWalletInfo(context.Context, *GetWalletInfoReq) (*GetWalletInfoResp, error)
	RelayTransferTxn(context.Context, *RelayTransferTxnReq) (*RelayTxnResp, error)
	RelayMessageTxn(context.Context, *RelayMessageTxnReq) (*RelayTxnResp, error)
	RelayTokenTxn(context.Context, *RelayTokenTxnReq) (*RelayTxnResp, error)
	RelayTransferTokenTxn(context.Context, *RelayTransferTokenTxnReq) (*RelayTxnResp, error)
	RelaySlaveTxn(context.Context, *RelaySlaveTxnReq) (*RelayTxnResp, error)
	ChangePassphrase(context.Context, *ChangePassphraseReq) (*ChangePassphraseResp, error)
	GetTransaction(context.Context, *TransactionReq) (*TransactionResp, error)
	GetBalance(context.Context, *BalanceReq) (*BalanceResp, error)
	GetOTS(context.Context, *OTSReq) (*OTSResp, error)
	GetHeight(context.Context, *HeightReq) (*HeightResp, error)
	GetBlock(context.Context, *BlockReq) (*BlockResp, error)
	GetBlockByNumber(context.Context, *BlockByNumberReq) (*BlockResp, error)
}

func RegisterWalletAPIServer(s *grpc.Server, srv WalletAPIServer) {
	s.RegisterService(&_WalletAPI_serviceDesc, srv)
}

func _WalletAPI_AddNewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).AddNewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/AddNewAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).AddNewAddress(ctx, req.(*AddNewAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_AddAddressFromSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAddressFromSeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).AddAddressFromSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/AddAddressFromSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).AddAddressFromSeed(ctx, req.(*AddAddressFromSeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_ListAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).ListAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/ListAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).ListAddresses(ctx, req.(*ListAddressesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_RemoveAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).RemoveAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/RemoveAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).RemoveAddress(ctx, req.(*RemoveAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_EncryptWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).EncryptWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/EncryptWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).EncryptWallet(ctx, req.(*EncryptWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_LockWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).LockWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/LockWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).LockWallet(ctx, req.(*LockWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_UnlockWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).UnlockWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/UnlockWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).UnlockWallet(ctx, req.(*UnlockWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetRecoverySeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecoverySeedsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetRecoverySeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetRecoverySeeds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetRecoverySeeds(ctx, req.(*GetRecoverySeedsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetWalletInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetWalletInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetWalletInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetWalletInfo(ctx, req.(*GetWalletInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_RelayTransferTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayTransferTxnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).RelayTransferTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/RelayTransferTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).RelayTransferTxn(ctx, req.(*RelayTransferTxnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_RelayMessageTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayMessageTxnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).RelayMessageTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/RelayMessageTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).RelayMessageTxn(ctx, req.(*RelayMessageTxnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_RelayTokenTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayTokenTxnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).RelayTokenTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/RelayTokenTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).RelayTokenTxn(ctx, req.(*RelayTokenTxnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_RelayTransferTokenTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayTransferTokenTxnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).RelayTransferTokenTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/RelayTransferTokenTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).RelayTransferTokenTxn(ctx, req.(*RelayTransferTokenTxnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_RelaySlaveTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelaySlaveTxnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).RelaySlaveTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/RelaySlaveTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).RelaySlaveTxn(ctx, req.(*RelaySlaveTxnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_ChangePassphrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePassphraseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).ChangePassphrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/ChangePassphrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).ChangePassphrase(ctx, req.(*ChangePassphraseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetTransaction(ctx, req.(*TransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetBalance(ctx, req.(*BalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetOTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTSReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetOTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetOTS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetOTS(ctx, req.(*OTSReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeightReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetHeight(ctx, req.(*HeightReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetBlock(ctx, req.(*BlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAPI_GetBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockByNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAPIServer).GetBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrl.WalletAPI/GetBlockByNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAPIServer).GetBlockByNumber(ctx, req.(*BlockByNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qrl.WalletAPI",
	HandlerType: (*WalletAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNewAddress",
			Handler:    _WalletAPI_AddNewAddress_Handler,
		},
		{
			MethodName: "AddAddressFromSeed",
			Handler:    _WalletAPI_AddAddressFromSeed_Handler,
		},
		{
			MethodName: "ListAddresses",
			Handler:    _WalletAPI_ListAddresses_Handler,
		},
		{
			MethodName: "RemoveAddress",
			Handler:    _WalletAPI_RemoveAddress_Handler,
		},
		{
			MethodName: "EncryptWallet",
			Handler:    _WalletAPI_EncryptWallet_Handler,
		},
		{
			MethodName: "LockWallet",
			Handler:    _WalletAPI_LockWallet_Handler,
		},
		{
			MethodName: "UnlockWallet",
			Handler:    _WalletAPI_UnlockWallet_Handler,
		},
		{
			MethodName: "GetRecoverySeeds",
			Handler:    _WalletAPI_GetRecoverySeeds_Handler,
		},
		{
			MethodName: "GetWalletInfo",
			Handler:    _WalletAPI_GetWalletInfo_Handler,
		},
		{
			MethodName: "RelayTransferTxn",
			Handler:    _WalletAPI_RelayTransferTxn_Handler,
		},
		{
			MethodName: "RelayMessageTxn",
			Handler:    _WalletAPI_RelayMessageTxn_Handler,
		},
		{
			MethodName: "RelayTokenTxn",
			Handler:    _WalletAPI_RelayTokenTxn_Handler,
		},
		{
			MethodName: "RelayTransferTokenTxn",
			Handler:    _WalletAPI_RelayTransferTokenTxn_Handler,
		},
		{
			MethodName: "RelaySlaveTxn",
			Handler:    _WalletAPI_RelaySlaveTxn_Handler,
		},
		{
			MethodName: "ChangePassphrase",
			Handler:    _WalletAPI_ChangePassphrase_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _WalletAPI_GetTransaction_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _WalletAPI_GetBalance_Handler,
		},
		{
			MethodName: "GetOTS",
			Handler:    _WalletAPI_GetOTS_Handler,
		},
		{
			MethodName: "GetHeight",
			Handler:    _WalletAPI_GetHeight_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _WalletAPI_GetBlock_Handler,
		},
		{
			MethodName: "GetBlockByNumber",
			Handler:    _WalletAPI_GetBlockByNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qrlwallet.proto",
}

func init() { proto.RegisterFile("qrlwallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x4f, 0x73, 0xdb, 0x44,
	0x14, 0x1f, 0xc5, 0x8e, 0x13, 0x3f, 0xdb, 0xb1, 0xb3, 0xf9, 0xa7, 0xaa, 0x69, 0x9b, 0x2c, 0x94,
	0x09, 0x2d, 0xd3, 0x4e, 0xcb, 0x70, 0x29, 0x30, 0x43, 0xd2, 0x69, 0xd3, 0x0e, 0xa5, 0x49, 0x15,
	0x77, 0x0a, 0x94, 0xe2, 0x51, 0xac, 0x4d, 0xec, 0x89, 0x2d, 0xc9, 0x5a, 0x25, 0x71, 0xae, 0x70,
	0xe2, 0xcc, 0x85, 0x1b, 0x27, 0x4e, 0x7c, 0x98, 0x1e, 0xf8, 0x0a, 0x7c, 0x07, 0xae, 0xcc, 0xdb,
	0x5d, 0xd9, 0xd2, 0x4a, 0x4d, 0x62, 0xa6, 0x33, 0xdc, 0xfc, 0xde, 0xee, 0xfb, 0xbd, 0x3f, 0xfb,
	0xd3, 0xee, 0x7b, 0x86, 0xfa, 0x20, 0xec, 0x9d, 0x3a, 0xbd, 0x1e, 0x8b, 0xee, 0x04, 0xa1, 0x1f,
	0xf9, 0xa4, 0x30, 0x08, 0x7b, 0x56, 0x79, 0x10, 0xf6, 0xa4, 0x6c, 0xad, 0x1e, 0xfa, 0xfe, 0x61,
	0x8f, 0xdd, 0x75, 0x82, 0xee, 0x5d, 0xc7, 0xf3, 0xfc, 0xc8, 0x89, 0xba, 0xbe, 0xc7, 0xe5, 0x2a,
	0xdd, 0x81, 0xc6, 0xa6, 0xeb, 0x3e, 0x67, 0xa7, 0x9b, 0xae, 0x1b, 0x32, 0xce, 0x6d, 0x36, 0x20,
	0xcb, 0x50, 0xea, 0xb0, 0xee, 0x61, 0x27, 0x32, 0x8d, 0x35, 0x63, 0xa3, 0x68, 0x2b, 0x89, 0x7c,
	0x00, 0xb5, 0x8e, 0xc3, 0x3b, 0xad, 0x83, 0x63, 0xaf, 0x8d, 0x18, 0xe6, 0xd4, 0x9a, 0xb1, 0x51,
	0xb6, 0xab, 0xa8, 0x7c, 0xac, 0x74, 0xf4, 0x15, 0xcc, 0x6b, 0x80, 0x3c, 0x20, 0x04, 0x8a, 0x6d,
	0xdf, 0x65, 0x02, 0xaf, 0x66, 0x8b, 0xdf, 0x64, 0x11, 0xa6, 0x59, 0x18, 0xfa, 0xa1, 0x42, 0x91,
	0x02, 0x31, 0x61, 0xc6, 0x91, 0x86, 0x66, 0x41, 0xe8, 0x63, 0x91, 0xde, 0x86, 0xa5, 0x4d, 0xd7,
	0x55, 0xa8, 0x8f, 0x43, 0xbf, 0xbf, 0xc7, 0x98, 0x8b, 0xe1, 0x12, 0x28, 0x72, 0xc6, 0x5c, 0x01,
	0x5e, 0xb6, 0xc5, 0x6f, 0xfa, 0x03, 0x2c, 0xe7, 0x6d, 0x7e, 0x4f, 0xa1, 0x10, 0x68, 0x3c, 0xeb,
	0xf2, 0x48, 0xc1, 0x33, 0x2c, 0x1a, 0x7d, 0x0d, 0xf3, 0x9a, 0x6e, 0x22, 0x67, 0xab, 0x50, 0x76,
	0x62, 0x53, 0xb3, 0xb0, 0x56, 0xd8, 0x28, 0xdb, 0x63, 0x05, 0xfd, 0x04, 0x1a, 0x36, 0xeb, 0xfb,
	0x27, 0x2c, 0x71, 0x4a, 0x89, 0xf0, 0x8c, 0x74, 0x78, 0x5f, 0xc2, 0xbc, 0xb6, 0x7b, 0x92, 0x50,
	0xe8, 0x7d, 0x68, 0x3c, 0xf2, 0xda, 0xe1, 0x59, 0x10, 0xbd, 0x12, 0xbc, 0x42, 0x67, 0xd7, 0x01,
	0x02, 0x87, 0xf3, 0xa0, 0x13, 0x3a, 0x9c, 0x29, 0x7f, 0x09, 0x0d, 0xba, 0xd4, 0x6c, 0x26, 0x72,
	0x79, 0x0f, 0xea, 0x2f, 0xbd, 0x9e, 0xdf, 0x3e, 0xba, 0xbc, 0xc7, 0x2f, 0xa0, 0x91, 0x36, 0x99,
	0xc8, 0x61, 0x1d, 0x6a, 0xcf, 0x92, 0xee, 0xe8, 0x03, 0x98, 0x7b, 0xf6, 0x5f, 0xc1, 0xee, 0xc2,
	0xc2, 0x36, 0x1a, 0xb5, 0xfd, 0x13, 0x16, 0x9e, 0x21, 0xd3, 0x2e, 0x38, 0xa0, 0x13, 0x58, 0xcc,
	0x1a, 0x4c, 0xca, 0xcd, 0x0e, 0x1b, 0x0a, 0xda, 0x2b, 0x6e, 0x2a, 0x91, 0x58, 0x30, 0xdb, 0xf7,
	0x58, 0xdf, 0xf7, 0xba, 0x6d, 0xb3, 0x28, 0x96, 0x46, 0x32, 0xf2, 0x76, 0x9b, 0xa9, 0x13, 0x7a,
	0xea, 0x1d, 0xf8, 0x98, 0xf8, 0xef, 0x06, 0xcc, 0x6b, 0xca, 0x49, 0x23, 0x39, 0x61, 0x21, 0xc7,
	0xeb, 0xa0, 0x20, 0x36, 0xc7, 0x22, 0x5e, 0x17, 0x2a, 0xe1, 0x56, 0xdb, 0x3f, 0xf6, 0x22, 0x11,
	0x4e, 0xd1, 0xae, 0x2a, 0xe5, 0x43, 0xd4, 0x91, 0x75, 0xa8, 0x76, 0x79, 0x8b, 0x49, 0xee, 0x30,
	0xd7, 0x9c, 0x5e, 0x33, 0x36, 0x66, 0xed, 0x4a, 0x97, 0x3f, 0x8a, 0x55, 0xf4, 0xad, 0x01, 0x0b,
	0x36, 0xeb, 0x39, 0x67, 0xcd, 0xd0, 0xf1, 0xf8, 0x01, 0x0b, 0x9b, 0x43, 0x0f, 0xeb, 0xbb, 0x0e,
	0xd5, 0xd1, 0x17, 0xd2, 0x8a, 0x7c, 0xd3, 0x10, 0x5f, 0x4d, 0x65, 0xa4, 0x6b, 0xfa, 0xe2, 0x08,
	0xfa, 0xe8, 0x87, 0x9b, 0x53, 0x6b, 0x85, 0x8d, 0xa2, 0x1d, 0x8b, 0xa4, 0x01, 0x85, 0x03, 0xc6,
	0x44, 0xc8, 0x45, 0x1b, 0x7f, 0x92, 0x9b, 0x30, 0xd7, 0x77, 0x78, 0xc4, 0xc2, 0x56, 0x7c, 0x6a,
	0xb2, 0x7c, 0x35, 0xa9, 0x55, 0xdf, 0x12, 0x6e, 0xe3, 0xdd, 0x43, 0x2f, 0xb1, 0x6d, 0x5a, 0x6e,
	0x93, 0xda, 0x78, 0xdb, 0x55, 0x28, 0xfb, 0x11, 0x6f, 0x75, 0x3d, 0x97, 0x0d, 0xcd, 0x92, 0xf0,
	0x32, 0xeb, 0x47, 0xfc, 0x29, 0xca, 0xf4, 0x4f, 0x03, 0x88, 0xc8, 0xe8, 0x1b, 0xc6, 0xb9, 0x73,
	0xc8, 0x54, 0x42, 0x26, 0xcc, 0xf4, 0xa5, 0x22, 0x26, 0x8c, 0x12, 0xe3, 0x68, 0xa7, 0xce, 0x8b,
	0xb6, 0x70, 0xb9, 0x68, 0x8b, 0x17, 0x46, 0x3b, 0xad, 0x45, 0xfb, 0xc7, 0x14, 0xde, 0x3e, 0x58,
	0x7f, 0xff, 0x88, 0x79, 0x2a, 0xd6, 0x65, 0x28, 0xf1, 0xb3, 0xfe, 0xbe, 0xdf, 0x53, 0xa1, 0x2a,
	0x09, 0x89, 0xe3, 0x39, 0x7d, 0xa6, 0x38, 0x22, 0x7e, 0x23, 0x71, 0xfc, 0x53, 0x8f, 0x85, 0x2a,
	0x44, 0x29, 0x20, 0x51, 0x5d, 0xd6, 0xee, 0xf6, 0x9d, 0x1e, 0x57, 0xcc, 0x18, 0xc9, 0xe9, 0xdb,
	0x70, 0x5a, 0xbb, 0x0d, 0x93, 0xa7, 0x5a, 0xca, 0x3d, 0xd5, 0x99, 0xf3, 0xea, 0x34, 0x7b, 0xb9,
	0x3a, 0x95, 0x2f, 0xac, 0x13, 0x68, 0x75, 0xfa, 0xc7, 0x00, 0x33, 0xcd, 0xd3, 0x44, 0xbd, 0x2e,
	0x41, 0xd6, 0x75, 0xa8, 0x46, 0x68, 0xd1, 0x8a, 0x86, 0xf8, 0xa2, 0xaa, 0x12, 0x56, 0x22, 0x89,
	0x82, 0xaa, 0x64, 0xe6, 0x85, 0xdc, 0xcc, 0x8b, 0xe7, 0x65, 0x3e, 0x7d, 0xb9, 0xcc, 0x4b, 0x17,
	0x66, 0x3e, 0xa3, 0x65, 0xfe, 0xd6, 0x50, 0x0c, 0xd9, 0xeb, 0x39, 0x27, 0x31, 0x9b, 0xaf, 0x42,
	0x99, 0xa3, 0xd8, 0x0a, 0x8e, 0xb8, 0x48, 0xb7, 0x6a, 0xcf, 0x0a, 0xc5, 0xee, 0x11, 0x17, 0xe5,
	0x68, 0xb7, 0xf1, 0x6a, 0x88, 0xce, 0x02, 0x26, 0xbf, 0xce, 0x9a, 0x5d, 0x91, 0xba, 0x26, 0xaa,
	0xfe, 0xdf, 0x2f, 0xf4, 0x7b, 0xa8, 0xca, 0xa3, 0xc4, 0x5c, 0x26, 0xba, 0x0f, 0xd7, 0x60, 0x2a,
	0x1a, 0x8a, 0xa8, 0x2b, 0xf7, 0x1b, 0x77, 0xb0, 0x0d, 0x13, 0x74, 0x70, 0x44, 0x77, 0x64, 0x4f,
	0x45, 0x43, 0xea, 0xc0, 0xc2, 0xc3, 0x8e, 0xe3, 0x1d, 0xb2, 0xdd, 0xd1, 0x6b, 0x86, 0xf5, 0xfa,
	0x10, 0x6a, 0x7e, 0xcf, 0xdd, 0xd5, 0xdf, 0xbc, 0xb4, 0x12, 0x77, 0x79, 0xec, 0x34, 0xb1, 0x4b,
	0x3a, 0x4f, 0x2b, 0xe9, 0x57, 0xb0, 0x98, 0x75, 0x31, 0xd1, 0x9b, 0xf6, 0x31, 0xcc, 0x25, 0xe3,
	0x66, 0x03, 0xb2, 0x02, 0x33, 0xd1, 0xb0, 0x25, 0x98, 0xa9, 0x3e, 0xf9, 0x68, 0xf8, 0xc4, 0xe1,
	0x1d, 0xfa, 0xb3, 0x01, 0xf5, 0xd4, 0xde, 0xf7, 0x5b, 0x2f, 0x4c, 0xb9, 0xed, 0x7b, 0x07, 0xdd,
	0xb0, 0x2f, 0x3b, 0x57, 0x45, 0xf2, 0xb4, 0x92, 0x7e, 0x04, 0xb0, 0xe5, 0xf4, 0x1c, 0xaf, 0xcd,
	0xce, 0x7f, 0x7b, 0x5f, 0x40, 0x65, 0xb4, 0x6f, 0xd2, 0x87, 0x6e, 0x5f, 0x1a, 0x2a, 0x4e, 0xc6,
	0x22, 0xa5, 0x50, 0xda, 0x69, 0xee, 0x9d, 0xef, 0xf6, 0x17, 0x03, 0x66, 0xc4, 0xa6, 0x89, 0x7c,
	0xae, 0x43, 0x15, 0x39, 0xba, 0xdf, 0x8d, 0x0e, 0xba, 0xac, 0xe7, 0x8a, 0x8f, 0xbe, 0x6a, 0x57,
	0xfc, 0x88, 0x6f, 0x29, 0x15, 0xb9, 0x07, 0x4b, 0x1e, 0x1b, 0x46, 0xad, 0x63, 0xef, 0x98, 0x33,
	0xb7, 0x35, 0xa6, 0xb4, 0xac, 0x12, 0xc1, 0xc5, 0x97, 0x62, 0x6d, 0x27, 0x26, 0x77, 0x05, 0xca,
	0x4f, 0x44, 0x47, 0x8f, 0xef, 0xff, 0x73, 0x80, 0x58, 0x98, 0x28, 0xb4, 0xf1, 0x90, 0x50, 0x48,
	0x0e, 0x09, 0xf4, 0x36, 0xcc, 0x6e, 0x61, 0x5b, 0x86, 0xe5, 0xb8, 0x01, 0x95, 0x0e, 0x73, 0x5c,
	0x16, 0x26, 0x69, 0x03, 0x52, 0x25, 0xa8, 0xf3, 0x0a, 0xca, 0x6a, 0xf3, 0x84, 0x9c, 0x99, 0xde,
	0x47, 0x33, 0x45, 0x1b, 0x10, 0xb4, 0x91, 0x40, 0x72, 0x81, 0x7e, 0x06, 0x0d, 0x21, 0x6f, 0x9d,
	0x3d, 0x3f, 0xee, 0xef, 0xb3, 0x50, 0x5d, 0xc1, 0x62, 0xb1, 0xe5, 0x09, 0x95, 0x1a, 0x6e, 0x2a,
	0x42, 0x27, 0x77, 0xdd, 0xff, 0xad, 0x0e, 0x65, 0xd9, 0x09, 0x6d, 0xee, 0x3e, 0x25, 0x6f, 0xa0,
	0x96, 0x1a, 0x65, 0xc8, 0x92, 0x70, 0xa4, 0xcf, 0x4b, 0xd6, 0x72, 0x9e, 0x9a, 0x07, 0xf4, 0xda,
	0x4f, 0x7f, 0xfd, 0xfd, 0xeb, 0xd4, 0x0a, 0x25, 0x62, 0xf6, 0x4a, 0xad, 0x3f, 0x30, 0x6e, 0x91,
	0x01, 0x90, 0xec, 0x8c, 0x42, 0xac, 0x18, 0x2c, 0x3b, 0xe9, 0x58, 0x57, 0xdf, 0xb9, 0xc6, 0x03,
	0x4a, 0x85, 0xb7, 0x55, 0xba, 0x12, 0x7b, 0xd3, 0x36, 0xa1, 0xcb, 0x37, 0x50, 0x4b, 0x0d, 0x29,
	0x2a, 0x23, 0x7d, 0x98, 0x51, 0x19, 0x65, 0xe6, 0x19, 0x2d, 0xa3, 0xd4, 0xba, 0x82, 0x4f, 0x0d,
	0x1e, 0x0a, 0x5e, 0x1f, 0x5d, 0x14, 0x7c, 0x66, 0x46, 0xd1, 0xe0, 0x53, 0xeb, 0x0a, 0x3e, 0x35,
	0x64, 0x28, 0x78, 0x7d, 0x58, 0x51, 0xf0, 0x99, 0x79, 0x44, 0x83, 0x4f, 0xad, 0x23, 0xfc, 0x0b,
	0x80, 0xf1, 0x08, 0x40, 0x88, 0x2c, 0x41, 0x72, 0x48, 0xb0, 0x16, 0x32, 0x3a, 0x1e, 0x50, 0x4b,
	0xa0, 0x2e, 0xd2, 0xba, 0xac, 0xc9, 0x68, 0x11, 0x21, 0xbf, 0x83, 0x6a, 0x72, 0x48, 0x21, 0x8b,
	0x02, 0x40, 0x1b, 0x75, 0xac, 0xa5, 0x1c, 0x2d, 0x0f, 0xe8, 0xaa, 0x00, 0x5e, 0xa6, 0xf3, 0x02,
	0x38, 0xb9, 0x8c, 0xd0, 0x5d, 0xd1, 0xcb, 0xa7, 0x66, 0x08, 0x62, 0x0a, 0xa0, 0x9c, 0x59, 0xc4,
	0xba, 0xf2, 0x8e, 0x15, 0x1e, 0xd0, 0x35, 0xe1, 0xc6, 0xa2, 0x4b, 0xc2, 0x8d, 0xbe, 0x45, 0xd5,
	0x3d, 0x35, 0x21, 0xa8, 0xba, 0xeb, 0xa3, 0x84, 0xaa, 0x7b, 0x66, 0x98, 0xd0, 0xea, 0x9e, 0x5a,
	0x47, 0x78, 0x27, 0x6e, 0x2f, 0xc7, 0xed, 0xbd, 0xca, 0x24, 0xa7, 0xeb, 0xb7, 0xe6, 0x13, 0x2b,
	0xf2, 0x71, 0xd6, 0x32, 0xd0, 0x8d, 0xd0, 0xc5, 0x8f, 0x50, 0xd7, 0xfa, 0x6d, 0xb2, 0x32, 0xc6,
	0x49, 0x75, 0xe1, 0x79, 0x0e, 0x6e, 0x08, 0x07, 0x57, 0xe8, 0xe2, 0xd8, 0xc1, 0xd8, 0x06, 0xf1,
	0xbf, 0x45, 0xe2, 0x27, 0x3a, 0xe4, 0x11, 0xf1, 0xd3, 0x5d, 0x73, 0x1e, 0xb6, 0xce, 0xf9, 0x84,
	0x05, 0x22, 0x07, 0xb0, 0x94, 0xdb, 0x53, 0x92, 0x6b, 0x39, 0x15, 0x3a, 0xdf, 0xd3, 0x4d, 0xe1,
	0xe9, 0x06, 0xb5, 0x72, 0xca, 0x94, 0xf0, 0x18, 0xe7, 0x12, 0xf7, 0x72, 0xc9, 0x5c, 0x12, 0xfd,
	0xdd, 0x25, 0x73, 0x89, 0x2d, 0x14, 0x65, 0xf5, 0xae, 0x44, 0x1d, 0x74, 0x4e, 0x3f, 0xa4, 0x28,
	0x9b, 0xd7, 0xc6, 0x68, 0x07, 0xae, 0x6f, 0x41, 0x57, 0xaf, 0x61, 0x6e, 0x9b, 0x45, 0x89, 0x4e,
	0x82, 0x2c, 0x64, 0x7a, 0x0b, 0x36, 0xb0, 0x16, 0xb3, 0x4a, 0x1e, 0xd0, 0xeb, 0x02, 0xde, 0xa4,
	0x0b, 0x31, 0x5f, 0x13, 0x1b, 0x10, 0xfc, 0x6b, 0x80, 0x6d, 0x16, 0xa9, 0x2e, 0x82, 0xd4, 0xe5,
	0xeb, 0x33, 0xea, 0x3d, 0xac, 0x46, 0x5a, 0x91, 0xb9, 0x22, 0xc6, 0xb6, 0x08, 0xf6, 0x39, 0x94,
	0xb6, 0x59, 0xb4, 0xd3, 0xdc, 0x23, 0x15, 0x61, 0x27, 0x3b, 0x09, 0xab, 0x3a, 0x16, 0x78, 0x40,
	0x97, 0x05, 0x40, 0x83, 0x56, 0x62, 0x80, 0x9d, 0xe6, 0x1e, 0x1a, 0x6f, 0x43, 0x79, 0x9b, 0x45,
	0xf2, 0xfd, 0x26, 0x73, 0xc2, 0x64, 0xf4, 0xb2, 0x5b, 0xf5, 0x94, 0xcc, 0x03, 0x7a, 0x45, 0xa0,
	0x2c, 0xd0, 0xb9, 0x18, 0x45, 0xae, 0x21, 0xd0, 0x43, 0x98, 0xc5, 0xb0, 0xf0, 0x8a, 0x21, 0xb5,
	0xc4, 0x73, 0xca, 0x06, 0xd6, 0x5c, 0x52, 0xe4, 0x01, 0x35, 0x05, 0x0a, 0xa1, 0xb5, 0x51, 0x32,
	0xb8, 0x24, 0x8b, 0xde, 0x88, 0xc5, 0xf8, 0xdd, 0x55, 0xe4, 0xd1, 0xdf, 0xe2, 0x0c, 0x68, 0xe6,
	0x12, 0x4a, 0x59, 0x3c, 0x30, 0x6e, 0xed, 0x97, 0xc4, 0xff, 0x95, 0x9f, 0xfe, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0x37, 0x36, 0xcd, 0xf0, 0x14, 0x00, 0x00,
}
